travis:
  secure:
    BINSTAR_TOKEN: 1GSWdX4yLs53crIwbEXRGxswxSeXRqE2jmZ4HpzBagdzTxWW6jqJsR/wWL/EKvaIqN6nsUgzrehrQ6MOmcEXyEg1H6zjK3QEDsXr4VxIOOrYeGAdOkOuNmyVJMdQpy/zHPy7MNMIUdKlEzIaoO/eVIFSBiN5OmlhiQj/zocrAOZBFAvTrftPUP/+wOJqmazfAuTNq5izOnxenFzjmQUnlK68OsIr98HQ2wo+/P7uj++0WfDwE5GU88dZT3I4n/kA6l+T7qN1tyMWTPrakfPFKfsO0D661t1teaho9cXzwy3lrFFINdtHIXui+UU44BDUwBnrAvHYIP70x5OM44w/c8fwBPF0DNtcqL0JzumIsTea5ERoNhF3/2+1CoDXFWhZvJleKaaxeXXoLgUPeBRo8tUgHXiNJ+A34zIlGsMMuLll2uu7nf+E2K32OM+lMNvs9uhmGMyXf+8AQ7mbuOcvNw0k/NDb6plv4PqYrgxKl09TTxs56jE/mlwc2Cpo9llTMhhFJLsUJMoH7KV+5M96+YWwcM0wZJEWilTbIsDJIczIVZ3G2EfJllp8Mi52P7/steMJM5Jvx2fj9EsXRmZZeoBhoAgoAb9AGAZPXixm1rRBLAR7xBbbIl+UHdaw99TOSNtfY/7lACT4+g9j+BqqsJiPXCEZEkpBo1qjzVdql2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
